/* Live weather: Open-Meteo. Zone geometry and static socio-demographics: illustrative demo data. */
const $ = id => document.getElementById(id);
const locations = [
  {id:'kedar',name:'Kedar settlement',coords:[30.3027,78.9774],residents:428,base:.65,cci:.64,vuln:.86,threshold:95,polygon:[[30.309,78.968],[30.314,78.978],[30.309,78.990],[30.299,78.989],[30.294,78.978],[30.299,78.969]]},
  {id:'bhatiya',name:'Bhatiya ward',coords:[30.2779,78.9896],residents:315,base:.56,cci:.72,vuln:.69,threshold:105,polygon:[[30.285,78.980],[30.289,78.991],[30.282,79.002],[30.272,79.000],[30.268,78.988],[30.274,78.979]]},
  {id:'jhakholi',name:'Jhakholi cluster',coords:[30.3195,79.0191],residents:201,base:.48,cci:.82,vuln:.51,threshold:110,polygon:[[30.326,79.008],[30.331,79.020],[30.325,79.032],[30.315,79.032],[30.311,79.020],[30.316,79.010]]}
];
const safeZones=[{name:'Pine Ridge shelter',coords:[30.292,79.033],capacity:820,available:612},{name:'Govt. Inter College',coords:[30.2575,78.961],capacity:540,available:315},{name:'Rudraprayag relief camp',coords:[30.2838,78.981],capacity:530,available:463}];
const state={selected:locations[0],weather:{rain:0,soil:.42,wind:0},layers:{},map:null};
const hsi=loc=>Math.min(1,loc.base*(1+.24*(state.weather.rain/loc.threshold)+.16*state.weather.soil));
const rps=loc=>.5*hsi(loc)+.25*(1-loc.cci)+.25*loc.vuln;
const level=loc=>hsi(loc)>=.75?'red':hsi(loc)>=.5?'orange':'green';
const colors={red:'#d64242',orange:'#e79a25',green:'#23845d'};
const fmt=n=>Number(n).toFixed(2);
const action=loc=>level(loc)==='red'?'Evacuate now':level(loc)==='orange'?'Prepare transport':'Monitor';
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3200)}
function markerIcon(loc){return L.divIcon({className:'',html:`<div class="hazard-marker ${level(loc)} ${level(loc)==='red'?'marker-pulse':''}"><span>▲</span></div>`,iconSize:[28,28],iconAnchor:[14,25]})}
const safeIcon=()=>L.divIcon({className:'',html:'<div class="safe-marker">✓</div>',iconSize:[25,25],iconAnchor:[12,12]});
function popup(loc){return `<div class="zone-popup"><b>${loc.name}</b><p><strong style="color:${colors[level(loc)]}">${level(loc).toUpperCase()} ZONE</strong> · ${loc.residents} residents</p><p><code>HSI ${fmt(hsi(loc))}</code> <code>CCI ${fmt(loc.cci)}</code> <code>RPS ${fmt(rps(loc))}</code></p><p>${action(loc)}</p></div>`}
function initMap(){if(!window.L){toast('Map library could not load. Check your internet connection.');return}const map=state.map=L.map('map',{zoomControl:false,preferCanvas:true}).setView([30.291,78.994],12);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);locations.forEach(loc=>{const polygon=L.polygon(loc.polygon,{color:colors[level(loc)],weight:2,fillColor:colors[level(loc)],fillOpacity:.34}).addTo(map);const marker=L.marker(loc.coords,{icon:markerIcon(loc),riseOnHover:true}).addTo(map).bindPopup(popup(loc));const choose=()=>selectLocation(loc,true);polygon.on('click',choose);marker.on('click',choose);state.layers[loc.id]={polygon,marker}});safeZones.forEach(zone=>L.marker(zone.coords,{icon:safeIcon()}).addTo(map).bindPopup(`<div class="zone-popup"><b>${zone.name}</b><p><strong style="color:#23845d">GREEN DESTINATION</strong></p><p>${zone.available} of ${zone.capacity} spaces available</p></div>`));$('fitZones').onclick=()=>map.flyToBounds(locations.flatMap(l=>l.polygon),{padding:[35,35],duration:1.05});setTimeout(()=>map.invalidateSize(),200)}
function selectLocation(loc,fly=false){state.selected=loc;if(fly&&state.map){state.map.flyTo(loc.coords,14,{animate:true,duration:1.15});state.layers[loc.id].marker.openPopup()}$('selectedZone').textContent=loc.name;$('selectedHsi').textContent=`HSI ${fmt(hsi(loc))}`;$('thresholdValue').textContent=loc.threshold;document.querySelectorAll('.table-row').forEach(row=>row.classList.toggle('selected-row',row.dataset.location===loc.id));loadWeather(loc)}
function renderMap(){locations.forEach(loc=>{const layer=state.layers[loc.id];if(!layer)return;const color=colors[level(loc)];layer.polygon.setStyle({color,fillColor:color,fillOpacity:loc.id===state.selected.id?.46:.32});layer.marker.setIcon(markerIcon(loc));layer.marker.bindPopup(popup(loc))});$('selectedHsi').textContent=`HSI ${fmt(hsi(state.selected))}`}
function renderRows(){const sorted=[...locations].sort((a,b)=>rps(b)-rps(a));$('habitationRows').innerHTML=sorted.map(loc=>`<div class="table-row" data-location="${loc.id}"><span><b>${loc.name}</b><small>${loc.residents} residents</small></span><span class="score ${level(loc)==='red'?'danger':level(loc)==='orange'?'warning':'safe'}">${fmt(hsi(loc))}</span><span class="score ${loc.cci<.75?'danger':'warning'}">${fmt(loc.cci)}</span><span><b class="rps ${level(loc)==='red'?'red-bg':level(loc)==='orange'?'orange-bg':'green-bg'}">${fmt(rps(loc))}</b></span><span>${action(loc)}</span></div>`).join('');document.querySelectorAll('.table-row').forEach(row=>row.onclick=()=>selectLocation(locations.find(l=>l.id===row.dataset.location),true))}
function renderDashboard(fallback=false){const atRisk=locations.filter(l=>hsi(l)>=.5),immediate=locations.filter(l=>rps(l)>=.75),people=immediate.reduce((sum,l)=>sum+l.residents,0);$('riskArea').textContent=`${(atRisk.length*4.6+state.weather.rain/38).toFixed(1)} km²`;$('riskHabitations').textContent=atRisk.length;$('riskPeople').textContent=people.toLocaleString('en-IN');$('riskTrend').textContent=`Live model at ${state.selected.name}`;$('habitationNote').textContent=`${immediate.length} need immediate action`;$('peopleNote').textContent=`RPS ≥ 0.75 · ${immediate.length} locations`;$('rainValue').textContent=`${state.weather.rain.toFixed(1)} mm`;$('soilValue').textContent=state.weather.soil.toFixed(2);$('windValue').textContent=`${state.weather.wind.toFixed(0)} km/h`;$('rainBar').style.width=`${Math.min(100,state.weather.rain/state.selected.threshold*100)}%`;$('soilBar').style.width=`${Math.min(100,state.weather.soil*100)}%`;const risk=level(state.selected),title=risk==='red'?'Immediate action recommended':risk==='orange'?'Elevated conditions detected':'Conditions currently within watch band';$('alertReason').innerHTML=`<b>${title}</b><br />HSI is ${fmt(hsi(state.selected))} for ${state.selected.name}: ${state.weather.rain.toFixed(1)} mm rainfall against a ${state.selected.threshold} mm threshold, with soil moisture normalised to ${state.weather.soil.toFixed(2)}.${fallback?' Showing offline demo values.':''}`;renderMap();renderRows()}
async function loadWeather(loc){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),9000);$('dataStatus').innerHTML='<i></i> Updating live data';$('weatherSource').textContent='Retrieving Open-Meteo model';try{const url=new URL('https://api.open-meteo.com/v1/forecast');url.search=new URLSearchParams({latitude:loc.coords[0],longitude:loc.coords[1],hourly:'precipitation,soil_moisture_0_to_7cm',current:'wind_speed_10m',past_days:'1',forecast_days:'1',timezone:'Asia/Kolkata'});const res=await fetch(url,{signal:controller.signal});if(!res.ok)throw Error(`Weather feed ${res.status}`);const data=await res.json(),hours=data.hourly?.time||[],precip=data.hourly?.precipitation||[],soil=data.hourly?.soil_moisture_0_to_7cm||[];const now=new Date().toLocaleString('sv-SE',{timeZone:'Asia/Kolkata',hour12:false}).slice(0,13).replace(' ','T');let index=hours.findIndex(time=>time>=now);if(index<0)index=hours.length-1;const rain=precip.slice(Math.max(0,index-23),index+1).reduce((sum,v)=>sum+(Number(v)||0),0),rawSoil=Number(soil[Math.max(0,index)])||.18;state.weather={rain,soil:Math.min(1,rawSoil/.45),wind:Number(data.current?.wind_speed_10m)||0};const stamp=new Date();$('dataStatus').innerHTML='<i></i> Live data connected';$('weatherSource').textContent='Live: Open-Meteo forecast model';$('mapDate').textContent=`LIVE · ${stamp.toLocaleString('en-IN',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'short'})} IST`;$('modelTimestamp').textContent=`Updated ${stamp.toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})} IST`;renderDashboard()}catch(error){state.weather={rain:43.6,soil:.64,wind:18};$('dataStatus').innerHTML='<i></i> Demo data mode';$('weatherSource').textContent='Offline illustrative fallback';$('mapDate').textContent='OFFLINE · illustrative scenario';$('modelTimestamp').textContent='Live source unavailable';renderDashboard(true);toast('Live weather unavailable; showing the built-in scenario.')}finally{clearTimeout(timer)}}
document.querySelectorAll('[data-panel]').forEach(button=>button.onclick=()=>{document.querySelectorAll('.panel,.nav-item').forEach(el=>el.classList.remove('active'));$(button.dataset.panel).classList.add('active');document.querySelector(`.nav-item[data-panel="${button.dataset.panel}"]`)?.classList.add('active');if(button.dataset.panel==='overview')setTimeout(()=>state.map?.invalidateSize(),250)});$('runBtn').onclick=()=>loadWeather(state.selected);$('locationMenu').onclick=()=>selectLocation(state.selected,true);$('exportBtn').onclick=()=>toast('Export hook ready: connect to your reporting system.');$('modelDetails').onclick=()=>toast('HSI and RPS formula details are shown in the live triggers panel.');
const inputs=['stability','recharge','infra','density','load'];function recalc(){const v=Object.fromEntries(inputs.map(id=>[id,Number($(id).value)]));inputs.forEach(id=>$(`${id}Out`).textContent=v[id].toFixed(2));const cci=(v.stability*v.recharge*v.infra)/(v.density*v.load),unstable=cci<1;$('cciNumber').textContent=Math.min(1.5,cci).toFixed(2);$('cciStatus').textContent=unstable?'Over-capacity / unstable':'Within carrying capacity';$('cciText').textContent=unstable?'Construction should be frozen and relocation planning initiated.':'Maintain monitoring and permit only resilient development.';$('cciNumber').style.color=unstable?'#d06232':'#16815b';$('cciMeter').style.left=`${Math.min(94,cci/1.5*100)}%`}inputs.forEach(id=>$(id).oninput=recalc);recalc();initMap();selectLocation(locations[0]);
